### ISSUE TITLE
Node.js Lv2과제 회고입니다! - 안희재

### ISSUE THREAD

**Issue by marioahn** [marioahn/nodebasic_lv2#1]
@diasm3

### Lv2과제를 진행하면서 Primary Key를 변경시키는 방법을 계속 고민하였습니다

- 가장 최근의 게시글을 삭제하고, 새로 게시글을 등록한다면, 새 게시글의 postId는 삭제 된 postId+1값을 가지게 됩니다. 
이 상태에서 게시글 전체 조회를 하게 된다면 postId가 다음과 같이 약간 어색한 모습이 됩니다
![1](https://github.com/marioahn/nodebasic_lv2/assets/89332401/367e471e-975e-45ac-a7d4-09271a428484)
- schema.prisma에서 `postId는 @id @default(autoincrement())`로 설정되어 있어서 계속 1씩 순차적으로 증가하게 되기 때문에 위와 같은 결과가 나오지만,
- **(1)이를 해결할 방법을 알고 싶습니다. 즉, 위 화면에서 가장 최신의 postId가 5가 되게 하는 방법이 있을까요?**
---
- 저는 처음에 게시글 생성 API안에서 PK를 변경시키는 코드를 짜보았지만, 작동하지 않았습니다.
**(2)PK는 변경이 아예 불가능한 것일까요?**
```javascript
/** 1. 게시글 생성API **/
router.post('/posts', async(req,res) => {
  const { user, title, content, password } = req.body;

  if (!user || !title || !content || !password) {
    return res.status(400).json({ errorMessage: '데이터 형식이 올바르지 않습니다'});
  }

  const post = await prisma.posts.create({
    data: { user, title, content, password }
  });

  // pk변경시켜보는 코드 -> 실패
  const posts = await prisma.posts.findMany({  // 전체 게시글 찾기 -> posts에 담음
    select: { postId: true, createdAt: true },
    orderBy: { createdAt: 'desc' }
  });
  if (!(post.postId - posts[1].postId)) {  // 가장 최근 게시글과의 pk값 차이가 1이 아니라면
    post.postId = posts[1].postId + 1
  }

  return res.status(200).json({ message: '게시글을 생성하였습니다' });
});
```

**Comment by diasm3** [comment]
1. 일단 soft delete 와 hard delete 의 차이점을 먼저 아셔야 합니다.
 - 현업에 가시면 DB를 진짜 삭제 하는(hard delete)하는 방식을 사용을 거의 안합니다. 왜냐하면 혹시모를 게시물을 복구를 해야할때가 옵니다. 물론 백업이라는 장치도 있고 해당 하는 부분만 복구를 할 수 있지만 soft delete로 deleted_at으로 언제 게시물이 삭제 되었을때 삭제 된 기록을 남기면서 해당 게시물을 숨김처리 하는 방식(soft delete)를 할 수 있습니다.
 - 그럼 hard delete를 할때는 번호가 이상하게 나온다 라고 생각할 수 있습니다. 하지만 이는 훨씬 안정적이고 번호가 꼬일수 없게 끔 설계가 미리 되어 있습니다. sql  스키마를 설정할때 아래와 같이 쿼리가 발생합니다.  만약에 이기능이 제대로 작동하지 않는다면 게시물 ID가 꼬여서 새로운 row가 생성되지 않게됩니다. 큰오류겠죠?
 - 혹시라도 이부분이 이상핫다면 UUID로 ID값이 생성되는 방식을 사용하시면 됩니다. [관련 글](https://www.baeldung.com/uuid-vs-sequential-id-as-primary-key)
 
<img width="987" alt="image" src="https://github.com/marioahn/nodebasic_lv2/assets/56494905/4e417229-2653-416f-9298-e911dfb9d8c8">

2. PK (Primary Key)는 한번 설정하고 나서는 수정을 안하는 것을 추천드립니다.
   - 그 이유는 PK와 연결된 다른 테이블에서의 결과값이 다 틀어지게 됩니다.
   - 아무튼 변경을 원하시면 drop primary key 하신다음 다시 하시면 됩니다. [관련 글](https://blog.naver.com/PostView.nhn?blogId=zzang9ha&logNo=222123598423)
   
<img width="691" alt="image" src="https://github.com/marioahn/nodebasic_lv2/assets/56494905/76663c46-580b-45b8-af7f-ae2679d10103">

**Comment by marioahn** [comment]
답변 정말 감사합니다 매니저님! 궁금했던 부분이 모두 해결 되었습니다. 
- PK가 새로 생성됨과 동시에 row data도 생성되기 때문에, PK를 조건에 따라 임의로 변경하려는 작업이 얼마나 큰 오류를 야기할 수 있는지 알게 되었습니다. 
- 해당 PK값이 다른 테이블과 연결되어 있는 경우, 이를 변경 시키려 한다면 다른 연관 테이블도 수정되기 때문에, 이 또한 예상치 못한 오류를 야기할 수 있다는 점을 인지하게 되었습니다
_( 현재 Post테이블의 postId는 외래키로서 & Comments테이블에 'PostId'컬럼으로 연결 되어 있습니다 )_
- 말씀 해주신 대로, `prisma/schema.prisma`에서  `postId @int @id @default(autoincrement()) ` 대신에,
 `postId String @id @default(uuid())`로 한번 바꿔서 다시 진행해보도록 하겠습니다. 여기서 uuid형태의 pk를 다시 가공하는 것은 제가 한번 구글링해서 진행해보도록 하겠습니다. 어떻게 해결할지 감이 안 잡혔는데, 덕분에 어느 부분에서 코드를 수정해야 할지에 대한 감과, 해결 방향이 잡혔습니다. 감사합니다!

- 현재: uuid
---
![1](https://github.com/marioahn/nodebasic_lv2/assets/89332401/cda4268b-7d76-4bdd-802f-10a2621adbb8)
---
 

+ps)제가 설명을 잘못했는데, 게시글 생성API에서 PK를 변경시켜주는 코드는 아래 if문까지 포함한 것이었습니다! 먼저, 현재의 전체 게시글(posts)을 findMany로 찾고, posts[0]은 방금 추가한 따끈따끈한 새 게시글, posts[1]은 생성 전의, 최근의 게시글을 각각 찾아서, postId를 비교해서 두 pk가 2이상 차이나면 차이를 1로 좁혀주는(임의로 pk를 변경시키는..) 코드였습니다. 매니저님 글을 읽고 나니 살짝 어이가 없는 코드였네요.. 😢


+ps)평일에 깃이슈 남겼다고, 메세지 드리려 했는데.. 태그가 제대로 작동하는 줄은 몰랐네요..주말에 답변 감사드립니다!
