### ISSUE TITLE
페어 리뷰

### ISSUE THREAD

**Issue by SHIN1501020** [marioahn/nodebasic_lv2#2]
안녕하세요! 페어 리뷰 진행하러 왔습니다 :)

1. prisma의 외래키를 사용해서 Posts와 Comments 관계를 1:N으로 구성한 부분이 좋았습니다. 외래키 사용시 `onDelete: Cascade`도 함께 작성 해주셨기 때문에 게시글이 삭제되면 댓글도 같이 삭제해서 데이터의 일관성을 유지해주신 부분이 매우 좋았습니다!

2. posts.route.js 에서 비밀번호가 맞지 않을 때 에러 처리를 해주는 부분이 좋았습니다. 다만 비밀번호를 검증하는 부분에서 비밀번호가 일치 할 때 실행되는 코드를 if문으로 묶었다면 코드가 조금 더 직관적이이 않았을까 싶습니다.

- 현재

`
else if (post.password !== password) {
      return res.status(401).json({ errorMessage: '비밀번호가 일치하지 않습니다' });
    };
    // 모든 조건을 통과했다면 수정작업 수행
    await prisma.posts.update({
      data: { title, content },
      where: {
        postId: +postId,
        password // 한 번 더 검증
      }
    });
`

- 예시

`
if (post.password === password) {
    await prisma.posts.update({
      data: { title, content },
      where: {
        postId: +postId,
        password // 한 번 더 검증
      }
    });
 }
else {
    return res.status(401).json({ errorMessage: '비밀번호가 일치하지 않습니다' });
}
`

3. comments.route.js 부분에서 req.body의 유효성 검사를 잘 해주셨습니다. 다만 유효성 검사 부분에서 '데이터 형식이 올바지 않습니다.'를 먼저 처리해주시는게 데이터 검사 순서에 알맞지 않았을까 싶습니다.

- 현재

`
    if (!content) {
      return res.status(400).json({ errorMessage: '댓글 내용을 입력해주세요' });
    } else if (!user || !password) {
      return res.status(400).json({ errorMessage: 'body데이터 형식이 올바르지 않습니다' })
    };
`

- 예시

`
    if (!user || !password) {
      return res.status(400).json({ errorMessage: 'body데이터 형식이 올바르지 않습니다' })
    } else if (!content) {
      return res.status(400).json({ errorMessage: '댓글 내용을 입력해주세요' });
    };
`

4. [routes]폴더로 route 경로를 기능 별로 분리해주셔서 코드 찾아서 읽기 편했습니다! 다만 posts와 comments의 api경로에 'posts'가 공통적으로 들어가기 때문에 이 부분을 별로 분리해서 작성해주시면 api경로 관리에 좋을 것 같습니다.

5. 에러처리 부분에서 !를 사용하는 것과 null을 사용하는게 섞여서 작성되어 있는 걸 보았습니다. 동일해도 문제 없는 코드들이었다고 생각되기 때문에 에러 처리 부분을 통일해서 작성해주면 코드가 좀 더 깔끔해질 것 같습니다!
`
//null로 처리하신 경우
if (post === null) { 
      return res.status(400).json({ errorMessage: '존재하지 않는 postId입니다' })
    }
//!로 처리하신 경우
if (!post) {
      return res.status(404).json({ errorMessage: '게시글 조회에 실패하였습니다' });
    }
`

6. 댓글을 수정/삭제하는 부분에서 비밀번호를 확인하는 로직이 누락되어있습니다. DB로 관련 내용을 충분히 처리할 수 있지만 코드적으로 한번 더 처리해주면 검증이 철저해지고 코드를 이해하기 조금 더 쉬워질 것 같습니다!

**Comment by marioahn** [comment]
혜훤님 & 준석님 리뷰 감사합니다!
- 피드백을 받고, 다시 한번 제 코드를 살펴보니 검증&에러 처리 부분에서 미흡한 점이 많았네요. 피드백 정말 감사드립니다!
- 말씀해 주신 점 모두 반영하여 코드를 수정했습니다😄
